services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
  api:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '3000:3000'
    